global_costmap:
    global_frame: /map
    robot_base_frame: /base_link
    update_frequency: 2.0  #地图更新的频率
    publish_frequency: 0.0  #地图发布出来显示更新的频率
    static_map: true
    rolling_window: false  #when static_map=true，rolling_window need to be set false
    transform_tolerance: 1.0  #指定tf变换中能容许的数据延迟的时间，这里为1s
    map_type: costmap

    plugins:
        - {name: static_layer, type: "costmap_2d::StaticLayer"}
        - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
        - {name: sonar_layer, type: "range_sensor_layer::RangeSensorLayer"}
        - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

    static_layer:                                                               
        unknown_cost_value: -1
        lethal_cost_threshold: 100
        map_topic: "map"
        first_map_only: false
        subscribe_to_updates: false
        track_unknown_space: true
        use_maximum: false
        trinary_costmap: true
   
    obstacle_layer:
        enable: true
        track_unknown_space: true
        footprint_clearing_enabled: true
        # combination_method: 1
        track_unknown_space: true
        observation_sources: scan
        scan: {sensor_frame: /laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true, inf_is_valid: true}

    sonar_layer:
        topics: ["/sonar"]
        no_reading_timeout: 1.0
        clear_threshold: 0.2
        mark_threshold: 0.8
        clear_on_max_reading: true

    inflation_layer:
        enable: true
        # inflation_radius: 0.45
        # cost_scaling_factor: 2.0
    
