local_costmap:
    publish_voxel_map: true
    global_frame: /map
    robot_base_frame: /base_link
    static_map: false
    rolling_window: true
    map_type: costmap
    update_frequency: 3.0   #3.0
    publish_frequency: 1.0   #1.0
    transform_tolerance: 0.2
    width: 6.0
    height: 6.0
    resolution: 0.02  #local cost map resolution>=gmapping map resolution
    origin_x: 0.0
    origin_y: 0.0

    plugins:
        - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
          # - {name: sonar_layer, type: "range_sensor_layer::RangeSensorLayer"}
        - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

    obstacle_layer:
        enabled: true
        footprint_clearing_enabled: true
        combination_method: 1
        max_obstacle_height: 2.0
        observation_sources: scan
        scan: {sensor_frame: /laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true, inf_is_valid: true}

        # sonar_layer:
        # sonatopics: ["/sonar"]
        # sonano_reading_timeout: 1.0
        # sonaclear_threshold: 0.2
        # sonamark_threshold: 0.8
        # sonaclear_on_max_reading: true

    inflation_layer:
        enabled: true
        inflation_radius: 1.0
        cost_scaling_factor: 2.0
        inflate_unknown: false
 
